name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python requirements
        run: pip install -r requirements.txt

      - name: run test
        run: coverage run -m pytest -v ./app/test

      - name: coverage report
        run: coverage report