name: CI

on:
  pull_request:
    branches:
      - main

concurrency: 
  group: CI-Pizza-Planet-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci-pizza-planet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to my branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run lint
        run: flake8 app/ manage.py

      - name: Run tests
        run: pytest -v app/test/
