name: ci_tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Analyzing the code with flake 8
        run: make lint

  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with pytest
        run: make test
  
  Tests-Coverage:
    needs: [Linters, Tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test coverage
        run: make ci-test-coverage

      - name: Get coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
