name: pizza_planet

on:
  pull_request:
    branches: ["main"]

jobs:
  ci-tests-pizza-planet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

      - name: Create and activate virtual enviroment Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate 
          pip3 install -r requirements.txt

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      
      - name: Start database
        run: |
          python3 manage.py db init
          python3 manage.py db migrate
          python3 manage.py db upgrade
      
      - name: Run tests
        run: |
          python manage.py test


