name: ci_tests_pizza_planet

on:
  pull_request:
    branches: ["main"]

jobs:
  ci-unit-tests-pizza-planet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          make install-dependencies

      - name: Start database
        run: |
          make start-database

      - name: Run test coverage
        run: |
          make run-coverage
