name: CI L'ultima cena
on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Create venv
        run: python3 -m venv venv

      - name: Set venv
        run: |
        source venv/bin/activate
        pip3 install -r requirements.txt
        export FLASK_ENV=development
      
      - name: Set database
        run: |
        python3 manage.py db init
        python3 manage.py db migrate
        python3 manage.py db upgrade
      
      - name: Set flask env
        run:  echo FINISHED!!!
